[package]
name = "rust_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "5.10.0"
serde = "1.0.193"
thiserror = "1.0.50"
rustyline = "12.0.0"